name: Upload Python Package

on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: exageraldo
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
